**Import Dependencies**

In [105]:
from requests import get
from bs4 import BeautifulSoup as Soup
import pandas as pd

**Getting URL**

In [106]:
url = get('https://imdb.to/3CzG7te')

***Parsing Data using Soup***

In [107]:
Soup_data = Soup(url.text, "html.parser")

In [108]:
#Finding all data using div
Movies = Soup_data.findAll("div",{'class':'lister-item mode-advanced'})

**Extracting Data from all**

In [109]:
name = []
time = []
for i in Movies:
  name.append(i.h3.a.text)
  time.append(i.p.find('span',{'class':'runtime'}).text.split()[0])

In [110]:
#wrapping all data into list
data = list(zip(name,time))

In [111]:
#Creating DataFrame
df = pd.DataFrame(data, columns=['name','time'])

In [112]:
#Creating New Column for desired output
df['complete'] = df['name'] + ' ' + df['time']

In [113]:
df

,name,time,complete
0,Avengers: Infinity War,149,Avengers: Infinity War 149
1,Black Panther,134,Black Panther 134
2,Deadpool 2,119,Deadpool 2 119
3,Bohemian Rhapsody,134,Bohemian Rhapsody 134
4,A Quiet Place,90,A Quiet Place 90
5,Spider-Man: Into the Spider-Verse,117,Spider-Man: Into the Spider-Verse 117
6,Green Book,130,Green Book 130
7,Venom,112,Venom 112
8,Aquaman,143,Aquaman 143
9,Ready Player One,140,Ready Player One 140
10,Ant-Man and the Wasp,118,Ant-Man and the Wasp 118
11,A Star Is Born,136,A Star Is Born 136
12,Solo: A Star Wars Story,135,Solo: A Star Wars Story 135
13,Bird Box,124,Bird Box 124
14,Mission: Impossible - Fallout,147,Mission: Impossible - Fallout 147
15,Annihilation,115,Annihilation 115
16,Jurassic World: Fallen Kingdom,128,Jurassic World: Fallen Kingdom 128
17,Hereditary,127,Hereditary 127
18,Incredibles 2,118,Incredibles 2 118
19,Fantastic Beasts: The Crimes of Grindelwald,134,Fantastic Beasts: The Crimes of Grindelwald 134
20,BlacKkKlansman,135,BlacKkKlansman 135
21,The Haunting of Hill House,572,The Haunting of Hill House 572
22,You,45,You 45
23,Game Night,100,Game Night 100
24,Ocean's Eight,110,Ocean's Eight 110
25,Tomb Raider,119,Tomb Raider 119
26,The Favourite,119,The Favourite 119
27,First Man,141,First Man 141
28,Red Sparrow,140,Red Sparrow 140
29,Upgrade,100,Upgrade 100
30,Cobra Kai,30,Cobra Kai 30
31,Crazy Rich Asians,120,Crazy Rich Asians 120
32,The Meg,113,The Meg 113
33,Altered Carbon,60,Altered Carbon 60
34,Isle of Dogs,101,Isle of Dogs 101
35,Rampage,107,Rampage 107
36,Bumblebee,114,Bumblebee 114
37,Searching,102,Searching 102
38,Ralph Breaks the Internet,112,Ralph Breaks the Internet 112
39,The Equalizer 2,121,The Equalizer 2 121
40,Roma,135,Roma 135
41,Halloween,106,Halloween 106
42,Bad Times at the El Royale,141,Bad Times at the El Royale 141
43,A Simple Favor,117,A Simple Favor 117
44,Sicario: Day of the Soldado,122,Sicario: Day of the Soldado 122
45,Vice,132,Vice 132
46,The Ballad of Buster Scruggs,133,The Ballad of Buster Scruggs 133
47,Succession,60,Succession 60
48,The Nun,96,The Nun 96
49,Maze Runner: The Death Cure,143,Maze Runner: The Death Cure 143

In [114]:
#Convert time column as number
df['time'] = pd.to_numeric(df.time)

In [116]:
t1 = int(input('Enter First Value: '))
t2 = int(input('Enter Second Value: '))

Enter First Value: 8
Enter Second Value: 26

**Creating List and then Comvert into Dictionary to access output as a key value pair**

In [117]:
values=[]
runtime = []
for i in range (t1-1,t2):
  values.append(df.loc[i]['complete'])
  runtime.append(df.loc[i]['time'])

In [118]:
com_dict = {runtime[i]: values[i] for i in range(len(runtime))}
com_dict = dict(sorted(com_dict.items()))
print(com_dict.get(list(com_dict)[-1]))

The Haunting of Hill House 572